config/routes.rb
Rails.application.routes.draw do
  root "recipes#index"
  
  resources :recipes
  namespace :recipes do
    resources :ingredients, only: [:new, :destroy]
  end

  resources :ingredients, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients, dependent: :destroy
  accepts_nested_attributes_for :ingredients, allow_destroy: true, reject_if: :all_blank
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def destroy
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      if @ingredient.destroy 
        format.turbo_stream
      end
    end
  end
end

app/controllers/recipes/ingredients_controller.rb
class Recipes::IngredientsController < ApplicationController
  def new
    @ingredient = Ingredient.new

    respond_to do |format|
      format.turbo_stream
    end
  end

  def destroy
    @id = params[:id]
    @ingredient = Ingredient.find_by(id: params[:id])

    respond_to do |format|
      format.turbo_stream
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end
  
  def new
    @recipe = Recipe.new(ingredients: [Ingredient.new])
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to root_path, notice: "Recipe was successfully created."
    end
  end

  def edit
    @recipe = Recipe.includes(:ingredients).find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update(recipe_params)
      redirect_to root_path, notice: "Recipe was successfully created."
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, ingredients_attributes: [:id, :name, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes/ingredients_helper.rb
module Recipes::IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NestedForms</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="bg-gray-50">
    <main class="p-10">
      <%= yield %>
    </main>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with model: recipe do |form| %>
  <div
    class="shadow sm:overflow-hidden sm:rounded-md"
    data-controller="request"
    data-request-url-value="<%= new_recipes_ingredient_path(format: :turbo_stream) %>">
    <div class="space-y-6 bg-white px-4 py-5 sm:p-6">
      <div class="grid grid-cols-3 gap-6">
        <div class="col-span-3 sm:col-span-2">
          <%= form.label :name, class: "block text-sm font-medium text-gray-700" %>
          <div class="mt-1 flex rounded-md shadow-sm">
            <%= form.text_field :name, class: "block w-full flex-1 rounded-md border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm", placeholder: "Carbonara" %>
          </div>
        </div>
      </div>

      <div class="relative">
        <div class="absolute inset-0 flex items-center" aria-hidden="true">
          <div class="w-full border-t border-gray-300"></div>
        </div>
        <div class="relative flex justify-start">
          <span class="bg-white pr-2 text-sm text-gray-500">Ingredients</span>
        </div>
      </div>

      <div id="ingredients" class="space-y-3" data-request-target="container">
        <% recipe.ingredients.each do |ingredient| %>
          <%= render "recipes/ingredient_fields", ingredient: ingredient %>
        <% end %>
      </div>

      <div class="relative">
        <div class="absolute inset-0 flex items-center" aria-hidden="true">
          <div class="w-full border-t border-gray-300"></div>
        </div>
        <div class="relative flex justify-center">
          <button type="button" class="bg-white px-2 text-gray-500" data-action="request#get">
            <svg class="h-5 w-5 text-gray-500" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path d="M10.75 4.75a.75.75 0 00-1.5 0v4.5h-4.5a.75.75 0 000 1.5h4.5v4.5a.75.75 0 001.5 0v-4.5h4.5a.75.75 0 000-1.5h-4.5v-4.5z" />
            </svg>
          </button>
        </div>
      </div>
    </div>
    <div class="bg-indigo-100 px-4 py-3 text-right sm:px-6">
      <%= form.submit "Save", class: "inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
    </div>
  </div>
<% end %>

app/views/recipes/_ingredient_fields.html.erb
<% id = ingredient.id || Time.now.to_i %>

<div id="ingredient_<%= id %>">
  <%= fields_for "recipe[ingredients_attributes][#{id}]", ingredient do |form| %>
    <%= form.hidden_field :id %>
    <%= form.hidden_field :_destroy, value: local_assigns[:destroy] || false %>
    
    <% unless local_assigns[:destroy] %>
      <div
        class="grid grid-cols-3 gap-6"
        data-controller="request"
        data-request-url-value="<%= recipes_ingredient_path(id, format: :turbo_stream) %>">
        <div class="col-span-3">
          <div class="flex rounded-md shadow-sm relative">
            <%= form.text_field :name, class: "block w-full flex-1 rounded-md border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm", placeholder: "Eggs" %>
            <% if local_assigns[:allow_remove] || ingredient.persisted? %>
              <button data-action="request#destroy" type="button" class="bg-red-100 absolute w-10 border border-gray-300 rounded-r-md right-0 top-0 bottom-0 flex items-center justify-center">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                </svg>
              </button>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/recipes/edit.html.erb
<div class="mx-auto p-10 my-20 rounded-lg">
  <div>
    <div class="md:grid md:grid-cols-3 md:gap-6">
      <div class="md:col-span-1">
        <div class="px-4 sm:px-0">
          <h3 class="text-base font-semibold leading-6 text-gray-900">Edit your <%= @recipe.name %> recipe 👩‍🍳</h3>
        </div>
      </div>
      <div class="mt-5 md:col-span-2 md:mt-0">
        <%= render 'form', recipe: @recipe %>
      </div>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="px-4 sm:px-6 lg:px-8">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-base font-semibold leading-6 text-gray-900">Recipes 👩‍🍳</h1>
      <p class="mt-2 text-sm text-gray-700">A list of all your tasty recipes.</p>
    </div>
    <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
      <%= link_to "Add Recipe", new_recipe_path, class: "block rounded-md bg-indigo-600 py-1.5 px-3 text-center text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600", data: { turbo_frame: "_top" } %>
    </div>
  </div>
  <div class="mt-8 flow-root">
    <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <table class="min-w-full divide-y divide-gray-300">
          <thead>
            <tr>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Name</th>
              <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-0">
                <span class="sr-only">Add Recipe</span>
              </th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-200">
            <% @recipes.each do |recipe| %>
              <tr>
                <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0"><%= recipe.name %></td>
                <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-0">
                  <%= link_to "Edit", edit_recipe_path(recipe), class: "text-indigo-600 hover:text-indigo-900" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/recipes/ingredients/destroy.turbo_stream.erb
<% if @ingredient %>
  <%= turbo_stream.replace "ingredient_#{@id}",
    partial: "recipes/ingredient_fields",
    locals: { ingredient: @ingredient, destroy: true } %>
<% else %>
  <%= turbo_stream.remove "ingredient_#{@id}" %>
<% end %>

app/views/recipes/ingredients/new.turbo_stream.erb
<%= turbo_stream.append "ingredients",
  partial: "recipes/ingredient_fields",
  locals: { ingredient: @ingredient, allow_remove: true } %>

app/views/recipes/new.html.erb
<div class="mx-auto p-10 my-20 rounded-lg">
  <div>
    <div class="md:grid md:grid-cols-3 md:gap-6">
      <div class="md:col-span-1">
        <div class="px-4 sm:px-0">
          <h3 class="text-base font-semibold leading-6 text-gray-900">Add a new recipe 👩‍🍳</h3>
        </div>
      </div>
      <div class="mt-5 md:col-span-2 md:mt-0">
        <%= render 'form', recipe: @recipe %>
      </div>
    </div>
  </div>
</div>